// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxtscpowabznlinzdpco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dHNjcG93YWJ6bmxpbnpkcGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDI3NDYsImV4cCI6MjA2NzgxODc0Nn0.Zj3auF6dUB1GXsQUGIMDx8INBIbtfJn8oX21T7EUkQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});